name: flutter_myspot
description: Animate spotlight following a desired scenario.
version: 0.1.0
homepage: https://github.com/mynumeric-mobile/flutter_myspot

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  audioplayers: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: